import { Theme } from "theme.slint";
import { AppLinks } from "applinks.slint";
import { Sidebar } from "sidebar.slint";
import { DashboardPanel } from "dashboard.slint";
import { SchedulePanel } from "schedule.slint";
import { TopicsPanel } from "topics.slint";
import { SpeakersPanel } from "speakers.slint";
import { SubmissionPanel } from "submission.slint";
import { PublicationPanel } from "publication.slint";
import { PapersPanel } from "papers.slint";

export component MainWindow inherits Window {
    title: "VHPC 2026";
    preferred-width: 900px;
    preferred-height: 600px;
    background: Theme.palette.pure-black;

    in-out property <int> active-panel: 0;

    Rectangle {
        width: 100%; height: 100%;
        background: Theme.palette.background-gradient;

        Rectangle {
            width: 50%;
            height: 100%;
            x: 0;
            background: Theme.palette.dark-left-gradient;
        }

        VerticalLayout {
            Sidebar {
                active-index: active-panel;
                navigate(idx) => {
                    active-panel = idx;
                }
            }

            Flickable {
                vertical-stretch: 1;
                viewport-height: inner.preferred-height;

                inner := VerticalLayout {
                    width: parent.width;
                    alignment: start;
                    if active-panel == 0 : DashboardPanel {}
                    if active-panel == 1 : SchedulePanel {}
                    if active-panel == 2 : TopicsPanel {}
                    if active-panel == 3 : SpeakersPanel {}
                    if active-panel == 4 : SubmissionPanel {}
                    if active-panel == 5 : PublicationPanel {}
                    if active-panel == 6 : PapersPanel {}
                }
            }
        }
    }
}
