import { Theme } from "theme.slint";
import { Sidebar } from "sidebar.slint";
import { DashboardPanel } from "dashboard.slint";
import { SchedulePanel } from "schedule.slint";
import { TopicsPanel } from "topics.slint";
import { SpeakersPanel } from "speakers.slint";
import { SubmissionPanel } from "submission.slint";

export component MainWindow inherits Window {
    title: "VHPC 2026";
    preferred-width: 900px;
    preferred-height: 600px;
    background: Theme.palette.pure-black;

    in-out property <int> active-panel: 0;

    Rectangle {
        width: 100%; height: 100%;
        background: Theme.palette.background-gradient;
        
        // Add the dark gradient on the left like Energy Monitor
        Rectangle {
            width: 50%;
            height: 100%;
            x: 0;
            background: Theme.palette.dark-left-gradient;
        }

        VerticalLayout {
            // Re-using the Sidebar file for now but renaming it structurally to act as the Header
            Sidebar {
                active-index: active-panel;
                navigate(idx) => {
                    active-panel = idx;
                }
            }

            Flickable {
                vertical-stretch: 1;
                viewport-height: self.height;

                if active-panel == 0 : DashboardPanel {}
                if active-panel == 1 : SchedulePanel {}
                if active-panel == 2 : TopicsPanel {}
                if active-panel == 3 : SpeakersPanel {}
                if active-panel == 4 : SubmissionPanel {}
            }
        }
    }
}
